FROM node:20-alpine AS builder
WORKDIR /app

COPY package*.json nx.json tsconfig.base.json ./
RUN npm ci

COPY . .

RUN npm run frontend:build

FROM nginx:alpine
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist/apps/frontend/browser /usr/share/nginx/html
EXPOSE 80